// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analyses.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAnalysisByUpload = `-- name: GetAnalysisByUpload :one
SELECT id, upload_id, currency, period_start, period_end, monthly_summary, category_totals, recurring_payments, anomalies, key_insights, savings_plan, chart_present, chart_forecast, raw_llm_json, created_at FROM analyses WHERE upload_id = $1
`

func (q *Queries) GetAnalysisByUpload(ctx context.Context, uploadID uuid.UUID) (Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByUpload, uploadID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Currency,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.MonthlySummary,
		&i.CategoryTotals,
		&i.RecurringPayments,
		&i.Anomalies,
		&i.KeyInsights,
		&i.SavingsPlan,
		&i.ChartPresent,
		&i.ChartForecast,
		&i.RawLlmJson,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysisIDByUpload = `-- name: GetAnalysisIDByUpload :one
SELECT id FROM analyses WHERE upload_id = $1
`

func (q *Queries) GetAnalysisIDByUpload(ctx context.Context, uploadID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAnalysisIDByUpload, uploadID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
