// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateTransactions implements pgx.CopyFromSource.
type iteratorForCreateTransactions struct {
	rows                 []CreateTransactionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTransactions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTransactions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AnalysisID,
		r.rows[0].TxnDate,
		r.rows[0].Description,
		r.rows[0].Counterparty,
		r.rows[0].Amount,
		r.rows[0].Direction,
		r.rows[0].BalanceAfter,
		r.rows[0].Category,
		r.rows[0].Essential,
		r.rows[0].Recurring,
	}, nil
}

func (r iteratorForCreateTransactions) Err() error {
	return nil
}

// Bulk-loaded rather than inserted one at a time: a year of statements is
// easily a few thousand rows, and COPY moves them in a single round trip
// inside the analyze step's transaction.
func (q *Queries) CreateTransactions(ctx context.Context, arg []CreateTransactionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"transactions"}, []string{"analysis_id", "txn_date", "description", "counterparty", "amount", "direction", "balance_after", "category", "essential", "recurring"}, &iteratorForCreateTransactions{rows: arg})
}
