// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID                uuid.UUID          `json:"id"`
	UploadID          uuid.UUID          `json:"upload_id"`
	Currency          string             `json:"currency"`
	PeriodStart       pgtype.Date        `json:"period_start"`
	PeriodEnd         pgtype.Date        `json:"period_end"`
	MonthlySummary    []byte             `json:"monthly_summary"`
	CategoryTotals    []byte             `json:"category_totals"`
	RecurringPayments []byte             `json:"recurring_payments"`
	Anomalies         []byte             `json:"anomalies"`
	KeyInsights       []byte             `json:"key_insights"`
	SavingsPlan       []byte             `json:"savings_plan"`
	ChartPresent      []byte             `json:"chart_present"`
	ChartForecast     []byte             `json:"chart_forecast"`
	RawLlmJson        []byte             `json:"raw_llm_json"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type TaskqMessage struct {
	SortKey       int64              `json:"sort_key"`
	ID            string             `json:"id"`
	Queue         string             `json:"queue"`
	Payload       []byte             `json:"payload"`
	Attempts      int32              `json:"attempts"`
	MaxRetry      int32              `json:"max_retry"`
	EnqueuedAt    pgtype.Timestamptz `json:"enqueued_at"`
	LockedUntil   pgtype.Timestamptz `json:"locked_until"`
	ReceiptHandle *string            `json:"receipt_handle"`
}

type Transaction struct {
	ID           int64          `json:"id"`
	AnalysisID   uuid.UUID      `json:"analysis_id"`
	TxnDate      pgtype.Date    `json:"txn_date"`
	Description  string         `json:"description"`
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	Direction    string         `json:"direction"`
	BalanceAfter pgtype.Numeric `json:"balance_after"`
	Category     string         `json:"category"`
	Essential    bool           `json:"essential"`
	Recurring    bool           `json:"recurring"`
}

type Upload struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	FailureReason *string            `json:"failure_reason"`
	FileCount     int32              `json:"file_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UploadFile struct {
	ID          uuid.UUID `json:"id"`
	UploadID    uuid.UUID `json:"upload_id"`
	Position    int32     `json:"position"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
	PageCount   *int32    `json:"page_count"`
	OcrMarkdown *string   `json:"ocr_markdown"`
}
