// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	GetUpload(ctx context.Context, id uuid.UUID) (Upload, error)
}

var _ Querier = (*Queries)(nil)
