// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateTransactionsParams struct {
	AnalysisID   uuid.UUID      `json:"analysis_id"`
	TxnDate      pgtype.Date    `json:"txn_date"`
	Description  string         `json:"description"`
	Counterparty string         `json:"counterparty"`
	Amount       pgtype.Numeric `json:"amount"`
	Direction    string         `json:"direction"`
	BalanceAfter pgtype.Numeric `json:"balance_after"`
	Category     string         `json:"category"`
	Essential    bool           `json:"essential"`
	Recurring    bool           `json:"recurring"`
}
