// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upload_files.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUploadFile = `-- name: CreateUploadFile :one
INSERT INTO upload_files (id, upload_id, position, filename, content_type, size_bytes, storage_key)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, upload_id, position, filename, content_type, size_bytes, storage_key, page_count, ocr_markdown
`

type CreateUploadFileParams struct {
	ID          uuid.UUID `json:"id"`
	UploadID    uuid.UUID `json:"upload_id"`
	Position    int32     `json:"position"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	StorageKey  string    `json:"storage_key"`
}

func (q *Queries) CreateUploadFile(ctx context.Context, arg CreateUploadFileParams) (UploadFile, error) {
	row := q.db.QueryRow(ctx, createUploadFile,
		arg.ID,
		arg.UploadID,
		arg.Position,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i UploadFile
	err := row.Scan(
		&i.ID,
		&i.UploadID,
		&i.Position,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.PageCount,
		&i.OcrMarkdown,
	)
	return i, err
}

const listUploadFiles = `-- name: ListUploadFiles :many
SELECT id, upload_id, position, filename, content_type, size_bytes, storage_key, page_count, ocr_markdown FROM upload_files
WHERE upload_id = $1
ORDER BY position
`

// Ordered by position so the statements are always presented to the model
// in the order the client submitted them.
func (q *Queries) ListUploadFiles(ctx context.Context, uploadID uuid.UUID) ([]UploadFile, error) {
	rows, err := q.db.Query(ctx, listUploadFiles, uploadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UploadFile{}
	for rows.Next() {
		var i UploadFile
		if err := rows.Scan(
			&i.ID,
			&i.UploadID,
			&i.Position,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.PageCount,
			&i.OcrMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
