// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (id, status, file_count)
VALUES ($1, $2, $3)
RETURNING id, status, failure_reason, file_count, created_at, updated_at
`

type CreateUploadParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	FileCount int32     `json:"file_count"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload, arg.ID, arg.Status, arg.FileCount)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FailureReason,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, status, failure_reason, file_count, created_at, updated_at FROM uploads WHERE id = $1
`

func (q *Queries) GetUpload(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FailureReason,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUploadStatus = `-- name: SetUploadStatus :one
UPDATE uploads
SET status         = $1,
    failure_reason = $2,
    updated_at     = now()
WHERE id = $3
RETURNING id, status, failure_reason, file_count, created_at, updated_at
`

type SetUploadStatusParams struct {
	Status        string    `json:"status"`
	FailureReason *string   `json:"failure_reason"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) SetUploadStatus(ctx context.Context, arg SetUploadStatusParams) (Upload, error) {
	row := q.db.QueryRow(ctx, setUploadStatus, arg.Status, arg.FailureReason, arg.ID)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FailureReason,
		&i.FileCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
