// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visualization.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const balanceOverTime = `-- name: BalanceOverTime :many
SELECT DISTINCT ON (txn_date)
    txn_date,
    balance_after::float8 AS balance
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
  AND balance_after IS NOT NULL
ORDER BY txn_date, id DESC
`

type BalanceOverTimeParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type BalanceOverTimeRow struct {
	TxnDate pgtype.Date `json:"txn_date"`
	Balance float64     `json:"balance"`
}

// One point per day: the closing balance, taken as the balance after the
// last transaction recorded for that day. Rows arrive in statement order,
// so the highest id on a given date is the latest one.
func (q *Queries) BalanceOverTime(ctx context.Context, arg BalanceOverTimeParams) ([]BalanceOverTimeRow, error) {
	rows, err := q.db.Query(ctx, balanceOverTime, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceOverTimeRow{}
	for rows.Next() {
		var i BalanceOverTimeRow
		if err := rows.Scan(&i.TxnDate, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryBreakdown = `-- name: CategoryBreakdown :many
SELECT
    COALESCE(NULLIF(category, ''), 'Uncategorised')::text  AS category,
    COALESCE(SUM(amount), 0)::float8                 AS amount,
    COUNT(*)::bigint                                 AS transaction_count
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
  AND direction = 'debit'
GROUP BY 1
ORDER BY 2 DESC, 1
`

type CategoryBreakdownParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type CategoryBreakdownRow struct {
	Category         string  `json:"category"`
	Amount           float64 `json:"amount"`
	TransactionCount int64   `json:"transaction_count"`
}

// Spending only: an income category is not a slice of a spending pie.
func (q *Queries) CategoryBreakdown(ctx context.Context, arg CategoryBreakdownParams) ([]CategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, categoryBreakdown, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryBreakdownRow{}
	for rows.Next() {
		var i CategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Amount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const essentialVsDiscretionary = `-- name: EssentialVsDiscretionary :many
SELECT
    to_char(date_trunc('month', txn_date), 'YYYY-MM')                  AS month,
    COALESCE(SUM(amount) FILTER (WHERE essential), 0)::float8          AS essential,
    COALESCE(SUM(amount) FILTER (WHERE NOT essential), 0)::float8      AS discretionary
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
  AND direction = 'debit'
GROUP BY 1
ORDER BY 1
`

type EssentialVsDiscretionaryParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type EssentialVsDiscretionaryRow struct {
	Month         string  `json:"month"`
	Essential     float64 `json:"essential"`
	Discretionary float64 `json:"discretionary"`
}

func (q *Queries) EssentialVsDiscretionary(ctx context.Context, arg EssentialVsDiscretionaryParams) ([]EssentialVsDiscretionaryRow, error) {
	rows, err := q.db.Query(ctx, essentialVsDiscretionary, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EssentialVsDiscretionaryRow{}
	for rows.Next() {
		var i EssentialVsDiscretionaryRow
		if err := rows.Scan(&i.Month, &i.Essential, &i.Discretionary); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionMonthBounds = `-- name: GetTransactionMonthBounds :one

SELECT
    MIN(date_trunc('month', txn_date))::date AS first_month,
    MAX(date_trunc('month', txn_date))::date AS last_month
FROM transactions
WHERE analysis_id = $1
`

type GetTransactionMonthBoundsRow struct {
	FirstMonth pgtype.Date `json:"first_month"`
	LastMonth  pgtype.Date `json:"last_month"`
}

// Chart aggregations for GET /api/v1/uploads/{id}/visualization.
// See conventions.go for the amount/direction conventions these depend on
// and for why money leaves the database as float8.
// Bounds the default window. Both columns are NULL when the analysis has
// no transactions at all, which the handler treats as an empty result
// rather than an error.
func (q *Queries) GetTransactionMonthBounds(ctx context.Context, analysisID uuid.UUID) (GetTransactionMonthBoundsRow, error) {
	row := q.db.QueryRow(ctx, getTransactionMonthBounds, analysisID)
	var i GetTransactionMonthBoundsRow
	err := row.Scan(&i.FirstMonth, &i.LastMonth)
	return i, err
}

const monthlyByCategory = `-- name: MonthlyByCategory :many
SELECT
    to_char(date_trunc('month', txn_date), 'YYYY-MM')  AS month,
    COALESCE(NULLIF(category, ''), 'Uncategorised')::text  AS category,
    COALESCE(SUM(amount), 0)::float8                   AS amount
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
  AND direction = 'debit'
GROUP BY 1, 2
ORDER BY 1, 3 DESC, 2
`

type MonthlyByCategoryParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type MonthlyByCategoryRow struct {
	Month    string  `json:"month"`
	Category string  `json:"category"`
	Amount   float64 `json:"amount"`
}

func (q *Queries) MonthlyByCategory(ctx context.Context, arg MonthlyByCategoryParams) ([]MonthlyByCategoryRow, error) {
	rows, err := q.db.Query(ctx, monthlyByCategory, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyByCategoryRow{}
	for rows.Next() {
		var i MonthlyByCategoryRow
		if err := rows.Scan(&i.Month, &i.Category, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyIncomeVsSpending = `-- name: MonthlyIncomeVsSpending :many
SELECT
    to_char(date_trunc('month', txn_date), 'YYYY-MM')                        AS month,
    COALESCE(SUM(amount) FILTER (WHERE direction = 'credit'), 0)::float8     AS income,
    COALESCE(SUM(amount) FILTER (WHERE direction = 'debit'), 0)::float8      AS spending
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
GROUP BY 1
ORDER BY 1
`

type MonthlyIncomeVsSpendingParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type MonthlyIncomeVsSpendingRow struct {
	Month    string  `json:"month"`
	Income   float64 `json:"income"`
	Spending float64 `json:"spending"`
}

func (q *Queries) MonthlyIncomeVsSpending(ctx context.Context, arg MonthlyIncomeVsSpendingParams) ([]MonthlyIncomeVsSpendingRow, error) {
	rows, err := q.db.Query(ctx, monthlyIncomeVsSpending, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyIncomeVsSpendingRow{}
	for rows.Next() {
		var i MonthlyIncomeVsSpendingRow
		if err := rows.Scan(&i.Month, &i.Income, &i.Spending); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowSummary = `-- name: WindowSummary :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE direction = 'credit'), 0)::float8                    AS total_income,
    COALESCE(SUM(amount) FILTER (WHERE direction = 'debit'), 0)::float8                     AS total_spending,
    COALESCE(SUM(amount) FILTER (WHERE direction = 'debit' AND essential), 0)::float8       AS essential_spending,
    COALESCE(SUM(amount) FILTER (WHERE direction = 'debit' AND recurring), 0)::float8       AS recurring_spending,
    COUNT(*)::bigint                                                                        AS transaction_count,
    COUNT(DISTINCT date_trunc('month', txn_date))::bigint                                   AS month_count
FROM transactions
WHERE analysis_id = $1
  AND txn_date >= $2
  AND txn_date <= $3
`

type WindowSummaryParams struct {
	AnalysisID  uuid.UUID   `json:"analysis_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type WindowSummaryRow struct {
	TotalIncome       float64 `json:"total_income"`
	TotalSpending     float64 `json:"total_spending"`
	EssentialSpending float64 `json:"essential_spending"`
	RecurringSpending float64 `json:"recurring_spending"`
	TransactionCount  int64   `json:"transaction_count"`
	MonthCount        int64   `json:"month_count"`
}

func (q *Queries) WindowSummary(ctx context.Context, arg WindowSummaryParams) (WindowSummaryRow, error) {
	row := q.db.QueryRow(ctx, windowSummary, arg.AnalysisID, arg.PeriodStart, arg.PeriodEnd)
	var i WindowSummaryRow
	err := row.Scan(
		&i.TotalIncome,
		&i.TotalSpending,
		&i.EssentialSpending,
		&i.RecurringSpending,
		&i.TransactionCount,
		&i.MonthCount,
	)
	return i, err
}
